### ISSUE TITLE
Bug: remote recording crashes when stopped on secondary port, produces empty maps on primary port

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#42]
Project: https://github.com/RafaelGoulartB/nodejs-ecommerce

When remote recording/stopping using the secondary (app) port, the agent spits out errors and no appmap is returned.
When doing the same with the primary port, empty appmaps are recorded.

[remote_error.log.2.txt](https://github.com/applandinc/appmap-agent-js/files/7455713/remote_error.log.2.txt)
[remote_error.log.txt](https://github.com/applandinc/appmap-agent-js/files/7455715/remote_error.log.txt)

**Comment by lachrist** [comment]
That one is tricky :|
Have encountered it elsewhere?

**Comment by lachrist** [comment]
I have trouble reproducing this bug. I have the `Cannot set headers after they are sent to the client` errors but not the critical `AssertionError: begin/end index mismatch`. Could you tell me the interactions you did to obtain it?

**Comment by lachrist** [comment]
So the `Cannot set headers after they are sent to the client` failure does not seem to be linked to the agent because it also happens without it. Here is how I produce the failure:

1. Launch via: `node index.js`
2. Fail login cf screenshot

<img width="1392" alt="Screenshot 2021-11-10 at 15 41 41" src="https://user-images.githubusercontent.com/5468597/141133703-ecf3b022-e5cc-46e9-a27b-eea189a35d32.png">

**Comment by ptrdvrk** [comment]
Works now, thank you.
